apiVersion: apps/v1
kind: Deployment
metadata:
  name: iswuf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iswuf
  template:
    metadata:
      labels:
        app: iswuf
    spec:
      containers:
        - name: iswuf
          image: konfle/iswu-frontend:latest
          ports:
            - containerPort: 80
