apiVersion: apps/v1
kind: Deployment
metadata:
  name: iswub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iswub
  template:
    metadata:
      labels:
        app: iswub
    spec:
      containers:
      - name: iswub
        image: konfle/iswu:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: iswub-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: iswub-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: iswub-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iswub-secret
              key: DB_PASSWORD
